spring:
  datasource:
    url: jdbc:h2:mem:workflowdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
  cache:
    type: simple
  data:
    redis:
      host: localhost
      port: 6379

cors:
  allowed-origins: "*"

aws:
  sqs:
    enabled: false

management:
  tracing:
    enabled: false

security:
  jwt:
    enabled: false

logging:
  json-structure:
    enabled: false
  level:
    com.aniri: DEBUG
    org.hibernate.SQL: DEBUG
